Pular para o conteúdo
Procure ou pule para...
Pedidos de puxar
Questões
Mercado
Explorar
 
@SOARESGG10 
SOARESGG10
/
SOARESGG10
Público
Código
Questões
Pedidos de puxar
Ações
Projetos
Wiki
Segurança
Insights
Configurações
Criar main.yml
 principal
@SOARESGG10
SOARESGG10 cometido há 1 hora 
1 pai 31adcae cometer b0b145d4fd789766e97901010256c771634d7dec
Exibição  com 25 adições e 0 exclusões.
 25  
.github/workflows/main.yml
@@ -0,0 +1,25 @@
nome: Gerar Dados

em:
 horário: # executar a cada 12 horas
 - cron: "* */12 * * * * *
  workflow_dispatch:

empregos:
 construir:
 nome: Empregos para atualizar dados
 em funcionamento: ubuntu-mais recente
 passos:
      # Animação cobra
 - usos: Platane/snk@master
        id: snake-gif
 com:
          github_user_name: SOARESGG10
          svg_out_path: dist/github-contribution-grid-snake.svg

 - usos: crazy-max/ghaction-github-pages@v2.1.3
 com:
 target_branch: saída
          build_dir: dist
        env:
 GITHUB_TOKEN: ${{ segredos. GITHUB_TOKEN }}
0 comentários sobre o compromisso b0b145d
@SOARESGG10
 
 
Deixe um comentário
Nenhum arquivo escolhido
Anexar arquivos arrastando e soltando, selecionando ou colando-os.
 Você está recebendo notificações porque está assistindo este repositório.
© 2022 GitHub, Inc.
Termos
Privacidade
Segurança
Estado
Docs
Entrar em contato com o GitHub
Precificação
API
Formação
Blogue
Sobre
