Cover image for Como adicionar o Snake Game no seu README do Github 🐍
Karol
Karol
Posted on 28 de mar.


1
Como adicionar o Snake Game no seu README do Github 🐍
#
github
#
tutorial
[Atualizado 2023]
Passo 1: Criando o Repositório
A primeira coisa que você deve fazer é criar um repositório público no seu GitHub com o nome do seu usuário. O GitHub vai entender que esse repositório possui um README especial de personalização e vai adicionar todas as alterações no seu overview.

Criando o seu repositório

Passo 2: Configurando seu GitHub actions
Antes de criar o seu workflow e adicionar o script, é importante que você ative algumas permissões que possivelmente estão desmarcadas no seu perfil.
Para alterar o que é necessário, entre no repositório que você criou e clique em settings > actions > general e ative as seguintes opções:
 

🔘 allow all actions and reusable workflows

Configurando actions - 1
 
🔘 read and write permissions

Configurando actions - 2

Passo 3: Criando o seu workflow
Agora que temos todas as permissões ativadas, vamos adicionar o script para gerar os arquivos necessários.
No seu repositório, clique em actions > new workflow e por fim clique em configurar simple workflow.

criando workflow

Quando você clicar vai abrir uma caixa de código, e é lá que vamos adicionar o nosso script! Apague todo o conteúdo predefinido e cole somente este:
name: Generate Datas

on:
  schedule: # execute every 12 hours
    - cron: "* */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      # Snake Animation
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: username #seu username
          svg_out_path: dist/github-contribution-grid-snake.svg

      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

Em #seu username coloque o seu nome de usuário no GitHub
alterando nome de usuário

Após todo esse processo, altere o nome do documento e clique em start commit. Seu workflow já está pronto para uso! Para dar start no processo, basta ir em actions > generate datas > run workflow.

workflow start

Se esse checkbox (✅) aparecer, parabéns, você fez tudo certo!
 

Passo 4: Personalizando README.md
Para finalizar, vá até o seu repositório, clique no README.md e cole o seguinte comando (⚠️lembre-se de colocar o seu nome de usuário no comando):

![snake gif](https://github.com/SEU_USUARIO/SEU_REPOSITORIO/blob/output/github-contribution-grid-snake.svg)

Agora você já têm a animação devorando todos os seus commits! :D

💚 Repositório do projeto Snake Game: Platane/snk
🖤 Meu github: https://github.com/mariakarolinesvg

Top comments (1)

Subscribe
pic
Add to the discussion
 
 
vitoriaft profile image
Vitória de Fátima Teixeira
•
18 de set.

Consegui fazer e roda normalmente, porém não mostra no meus commits


1
 like
Like
Reply
Code of Conduct • Report abuse
profile
JetBrains
PROMOTED

Jetbrains Academy

Build your first app and gear up for interviews with JetBrains Academy
Whether you're just starting your journey into the coding world or preparing for a tech interview, choosing the right approach is critical.

JetBrains Academy lets you choose between real-world projects, interactive courses in a smart IDE, or university programs. You can choose the learning approach and level that fits you best.

Take Java, for example. It's a versatile language known for its use in various applications. With JetBrains Academy, you can build your first desktop app with Swing or jump into backend development with Spring Boot.

For those with a job interview on the horizon, check out our free Algorithmic Challenges in Kotlin course. Covering over 30 unique algorithms, this course is your guide to acing the most challenging interview questions.

Sign up for free

Read next
olgabraginskaya profile image
The Data Engineering Docker-Compose Starter Kit
Olga Braginskaya - Sep 22

marcuskohlberg profile image
How to build a Slack Bot in Go
marcuskohlberg - Sep 22

dmitry-kabanov profile image
How to mirror GitLab repo to GitHub
Dmitry Kabanov - Aug 23

pratikfagadiya profile image
WTF is version control thing ? Learn Git — Beginner Edition (Part 1)
Pratik Fagadiya - Sep 10


Karol
Follow
💜Materializando ideias em códigos desde 2019!
EDUCATION
Instituto Federal de Educação, Ciência e Tecnologia.
JOINED
28 de mar. de 2023
Trending on DEV Community 
Victor Gerbrands profile image
Building a store for digital products with Next.js and Medusa
#nextjs #medusajs #javascript #tutorial
CodeItBro profile image
10 Github repositories to achieve Python mastery
#beginners #tutorial #opensource #python
dev.to staff profile image
Is GitHub Copilot a Game-Changer?
#discuss
DEV Community

🌚 Life is too short to browse without dark mode
You can customize your theme, font, and more when you are signed in.

name: Generate Datas

on:
  schedule: # execute every 12 hours
    - cron: "* */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      # Snake Animation
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: SOARESGG10
          svg_out_path: dist/github-contribution-grid-snake.svg

      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
